/*
 *	Author:  
 *  Date: 
*/

package pkg;
import java.util.Scanner;
import java.util.Random;


public class BaseClass {
	public String starboy = "Im tryna put you in the worst mood ah P1 cleaner than your church shoes ah Milli point two just to hurt you ah All red Lamb just to tease you ah None of these toys on lease too ah Made your whole year in a week too yeah Main girl outta your league too ah Side girl out of your league too ah House so empty need a centerpiece Twenty racks a table cut from ebony Cut that ivory into skinny pieces Then she clean it with her face man I love my baby ah You talking money need a hearing aid You talking bout me I dont see the shade Switch up my style I take any lane I switch up my cup I kill any pain Look what youve done Im a motherfreaking starboy Look what youve done Im a motherfreaking starboy Every day a person try to test me ah Every day a person try to end me ah Pull off in that Roadster SV ah Pockets overweight getting hefty ah Coming for the king thats a far cry ah I come alive in the fall time I The competition I dont really listen Im in the blue Mulsanne bumping New Edition House so empty need a centerpiece Twenty racks a table cut from ebony Cut that ivory into skinny pieces Then she clean it with her face man I love my baby ah You talking money need a hearing aid You talking bout me I dont see the shade Switch up my style I take any lane I switch up my cup I kill any pain Look what youve done Im a motherfreaking starboy Look what youve done Im a motherfreaking starboy Let a person brag Pitt Legend of the fall took the year like a bandit Bought mama a crib and a brand new wagon Now she hit the grocery shop looking lavish Star Trek roof in that Wraith of Khan Girls get loose when they hear this song A hundred on the dash get me close to God We dont pray for love we just pray for cars House so empty need a centerpiece Twenty racks a table cut from ebony Cut that ivory into skinny pieces Then she clean it with her face man I love my baby ah You talking money need a hearing aid You talking bout me I dont see the shade Switch up my style I take any lane I switch up my cup I kill any pain Look what youve done Im a motherfreaking starboy Look what youve done Im a motherfreaking starboy Look what youve done Im a motherfreaking starboy Look what youve done Im a motherfreaking starboy";
 	public String xoTheHost = "Shots of the Henny bottles of Patron Blunts to your face you dont wanna sing no more lost your C notes Cabbed all day took the bus back home Evictions on your door blame it on the weed blame it on the booze Blame it on the night life lights passing you yeah Just dont blame it on me that you wanna come and party With a person like me cause I get it Youre built like a Goddess And it seems like you been stressing Specially when your nose red From that K special Diet Coke You need more bread now you got no rent You blow that money money You try to window shop you blow another hundred Shes messing with goons in the day Hipster nights downtown and your daddy dont know youre out If they dont let you in You know where to find me Cause if you wanna go again You can always call me Cause all we ever do is love Open up your mind you can find the love Girl you aint alone we all been alone Baby just be honest woo dont you forget XO dont you worry bout a thing XO well be everything you need just believe XO yeah XO yeah whoa I love it when your eyes are red oh yeah Are you on my cloud yet Cause I got a brand new cam can we video feed can we POV Why I wanna catch you at your best When your hairs a mess You look so depressed And youre filled with regret And you feel like you gotta go home Cause these nights pass so much quicker than the days did Same clothes you aint ready for your day shift But you up you need money for your face lift Lust over love is your mindset Waking up with most of your side wet Another room you hear your mom crying Cause she found your bag stuffed in the laundry And the Bacardi from the last party If they wont let you in You know where to find me oh And if you wanna go again You can always call me Cause all we ever do is love Open up your mind you can find the love Girl you aint alone we all been alone Baby just be honest ooh dont you forget XO no no dont you worry bout a thing XO well be everything you need just believe yeah XO yeah XO ooh whoa I need I need something from you Oh theres so much love to pass around Theres too much love Girl the nights almost done And who you came with is already gone You said you want me But I remember who you are And girl it wasnt long ago Didnt think Id go this far Well I got a test for you You said you want my heart Well baby you can have it all Theres just something that I Need from you is to meet my boys I got a lot of boys And we can make you right And if you get too high Baby come over here and ride it out Oh oh oh yeah Ride it out Oh oh whoa yeah Ride it out Ride it out Just ride it";
 	public String wickedGames = "I left my girl back home I dont love her no more And shell never even know that These eyes that Im staring at Let me see that Look at all this cash And I emptied out my cards too Now Im leaning on that Bring your love baby I could bring my shame Bring the drugs baby I could bring my pain I got my heart right here I got my scars right here Bring the cups baby I could bring the drank Bring your body baby I could bring you fame And thats my words too Just let me love you Listen ma Ill give you all I got Get me off of this I need confidence in myself Yeah yeah yeah ohh yeah ohh Listen ma Ill give you all of me Give me all of it I need all of it to myself Whoa-whoa whoa So tell me you love me Only for tonight only for the night Even though you dont love me Oh-whoa oh-whoa Just tell me you love me Ill give you what I need Ohh-yeah Ill give you all of me Even though you dont love me Oh-whoa Yeah yeah Oh-whoa Yeah yeah Uh let me see you dance I love to watch you dance Take you down another level And get you dancing with the Devil Take a shot of this But Im warning you Im on that thing that you cant smell baby So put down your perfume Bring your love baby I could bring my shame Bring the drugs baby I could bring my pain Oh I got my heart right here Oh I got my scars right here Bring the cups baby I could bring the drank Bring your body baby I could bring you fame And thats my words too ayy So let me love you Listen ma Ill give you all I got Get me off of this off of this I need confidence confidence in myself Ohh oh ayy ayy ayy Listen ma Ill give you all of me ooh Give me all of it I need all of it to myself I need all of it so tell me you love me yeah Only for tonight Ohh Only for the night Even though you dont love me yeah Oh-whoa Ohh Oh-whoa Just tell me you love me Ill give you what I need Ohh-oh Ill give you all of me Even though you dont love me ohh yeah Oh-whoa oh-whoa Ohh";
 	public String trustIssuesRemix = "All she cares about is money And the city where shes from Her intention is the paper She dont need no love She spilling all this liquor Trying to pass me all these cups Well babygirl Im zoning Somebody shouldve told her I popped one Forget it I popped one Oh girl Im on one Forget it I popped one I popped one Girl Im lying Im on a few Dont you worry this aint new Can we take this to your spot Im on eviction number two Cause I popped one oh Forget it I popped one Oh yeah Ooh yeah ooh yeah ooh yeah Ooh yeah ooh yeah Trust issues Ooh yeah ooh yeah Ooh yeah ooh yeah ooh woah Do you know whats going on over here I do I do I do Have you even bothered to look I did oh I did Well if you know then let me know We dont gotta be running in these circles In these circles no more Trust issues Trust issues Trust issues Trust issues Trust issues Oh yeah Trust issues no more Trust issues no more Trust issues no more Oh yeah Trust issues Oh Trust issues Yeah yeah yeah woah Yeah yeah yeah oh Yeah yeah yeah woah Ooh woah ooh yeah ooh yeah";
	public String [] songs  = {"Starboy", "XO/The Host", "Wicked Games", "Trust Issues"};
 	public String [] lyrics = {starboy, xoTheHost, wickedGames, trustIssuesRemix};
 	
 	public BaseClass() {
		
 	
	}

}
